### ISSUE TITLE
Add spec for users behavior

### ISSUE THREAD

**Issue by etagwerker** [ombulabs/harvesting#10]
@benphelps introduced new users behavior in #9. We should add a spec to cover this new behavior.

**Comment by krishna543019** [comment]
Hi,
Are you adding invoices, invoice_line_items soon ? That would be much helpful to this great gem

Thanks

**Comment by etagwerker** [comment]
@krishna543019 I don't have any plans to do that soon. If anyone is interested in doing that, we welcome pull requests with open arms 😄 -- someone made some progress over here: https://github.com/ombulabs/harvesting/pull/35/files -- feel free to continue their work 👍

**Comment by etagwerker** [comment]
I see that there is now a spec for client#users. So I'm closing this issue.
