### ISSUE TITLE
OAuth2 Authentication 

### ISSUE THREAD

**Issue by SupasitW** [ombulabs/harvesting#21]
I use you gem for my application but I can see how to authentication by using OAuth2.

In harvest api they say harvest v2 can authenticate by OAuth2 

https://help.getharvest.com/api-v2/authentication-api/authentication/authentication/#scopes-and-account-access

Could you please guide me how to authenticate with OAuth2 ?

**Comment by etagwerker** [comment]
@SupasitW Sorry for the delay! Did you find a solution for this? It sounds like a feature that is not yet supported in this library.

**Comment by SupasitW** [comment]
@etagwerker  Hi , I use OAuth flow from harvest website , After i get harvest id and access_token  I use your gem to get project , client data.

1. create app at https://id.getharvest.com/developers

2. Login with https://id.getharvest.com/oauth2/authorize?client_id=XXXXXX&response_type=code  
Client Id: XXXXXX
Client Secret: XXXXYYYYZZZZ

Get this by capture the response 
code : 244784.ac.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

3. Run this Or use Postman

Run: 

curl -X POST \
  -H "Content-Type: application/json" \
  -H "User-Agent: MyApp (yourname@example.com)" \
  --data-urlencode "code=244784.ac.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" \
  --data-urlencode "client_id=XXXXXX" \
  --data-urlencode "client_secret=XXXXYYYYZZZZ" \
  --data-urlencode "grant_type=authorization_code" \
  'https://id.getharvest.com/api/v2/oauth2/token'

{
    "access_token": "244784.at.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "refresh_token": "244784.rt.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "token_type": "bearer",
    "expires_in": 1209599
}

4. Get Harvest Id 
curl "https://id.getharvest.com/api/v2/accounts" \
  -H "Authorization: Bearer 244784.at.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" \
  -H "User-Agent: MyApp (yourname@example.com)"

{"user":{"id":244784,"first_name":"MyHarvestName","last_name":"MyHarvestLastName","email":""},"accounts":[{"id":255783,"name":"My Harvest","product":"harvest","google_sign_in_required":false}]}

after this I've got harvest_id and access_token to use your GEM
