### ISSUE TITLE
Bump Gem version

### ISSUE THREAD

**Issue by k2heikkila** [ombulabs/harvesting#47]
There have been many changes since the 0.3.0 release 17 months ago.  Do you plan on bumping the Gem version with the latest from master? Many thanks for maintaining this gem!

**Comment by etagwerker** [comment]
@k2heikkila That is a good idea. Could you help us by submitting a PR that updates RELEASE_NOTES.md? That will help us get closer to a release.

**Comment by k2heikkila** [comment]
@etagwerker Will do.  It's going to be pretty difficult to tell whether there are breaking changes from the commits, but happy to summarize what I can tell.

**Comment by etagwerker** [comment]
@k2heikkila Done -> https://rubygems.org/gems/harvesting/versions/0.4.0
